<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HO3NPSQ" failures="2" tests="20" name="seleniumtestng.TestNGAnnot" time="0.068" errors="0" timestamp="2021-04-08T11:12:51 IST" skipped="5">
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginPass" time="0.009"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginPriority0" time="0.007"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testHomePage" time="0.000">
    <skipped/>
  </testcase> <!-- testHomePage -->
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.003"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.002"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.009"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.005"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.004"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.003"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginPriority0" time="0.003"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.010"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.002"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.000"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginRefersh" time="0.005"/>
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testSuccessLogin" time="0.004">
    <failure message="" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:44)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:53)
at seleniumtestng.TestNGAnnot.testSuccessLogin(TestNGAnnot.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1213)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSuccessLogin -->
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginPriority1" time="0.002">
    <failure message="" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:44)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:53)
at seleniumtestng.TestNGAnnot.testLoginPriority1(TestNGAnnot.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1213)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testLoginPriority1 -->
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginPriority2" time="0.000">
    <skipped/>
  </testcase> <!-- testLoginPriority2 -->
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginFail">
    <skipped/>
  </testcase> <!-- testLoginFail -->
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginFail">
    <skipped/>
  </testcase> <!-- testLoginFail -->
  <system-out/>
  <testcase classname="seleniumtestng.TestNGAnnot" name="testLoginFail">
    <skipped/>
  </testcase> <!-- testLoginFail -->
  <system-out/>
</testsuite> <!-- seleniumtestng.TestNGAnnot -->
